package cert

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"os"
	"time"

	"github.com/notaryproject/notation-core-go/testhelper"
	"github.com/notaryproject/notation-go/config"
	"github.com/notaryproject/notation-go/dir"
	"github.com/notaryproject/notation/cmd/notation/internal/truststore"
	"github.com/notaryproject/notation/internal/osutil"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

var (
	keyDefaultFlag = &pflag.Flag{
		Name:  "default",
		Usage: "mark as default signing key",
	}
	setKeyDefaultFlag = func(fs *pflag.FlagSet, p *bool) {
		fs.BoolVarP(p, keyDefaultFlag.Name, keyDefaultFlag.Shorthand, false, keyDefaultFlag.Usage)
	}
)

type certGenerateTestOpts struct {
	name      string
	bits      int
	isDefault bool
	cleanup   bool
}

func certGenerateTestCommand(opts *certGenerateTestOpts) *cobra.Command {
	if opts == nil {
		opts = &certGenerateTestOpts{}
	}
	command := &cobra.Command{
		Use:   "generate-test [flags] <common_name>",
		Short: "Generate a test RSA key and a corresponding self-signed certificate.",
		Args: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return errors.New("missing certificate common_name")
			}
			opts.name = args[0]
			return nil
		},
		Long: `Generate a test RSA key and a corresponding self-signed certificate

Example - Generate a test RSA key and a corresponding self-signed certificate named "wabbit-networks.io":
  notation cert generate-test "wabbit-networks.io"

Example - Generate a test RSA key and a corresponding self-signed certificate, set RSA key as a default signing key:
  notation cert generate-test --default "wabbit-networks.io"
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return generateTestCert(opts)
		},
	}

	command.Flags().IntVarP(&opts.bits, "bits", "b", 2048, "RSA key bits")
	setKeyDefaultFlag(command.Flags(), &opts.isDefault)
	command.Flags().BoolVar(&opts.cleanup, "cleanup", false, "delete the key and certificate generated by generate-test")
	return command
}

func generateTestCert(opts *certGenerateTestOpts) error {
	// initialize
	name := opts.name
	if !truststore.IsValidFileName(name) {
		return errors.New("name needs to follow [a-zA-Z0-9_.-]+ format")
	}

	// check clean up
	if opts.cleanup {
		return generateTestCleanUp(name)
	}

	// generate RSA private key
	bits := opts.bits
	fmt.Println("generating RSA Key with", bits, "bits")
	key, keyBytes, err := generateTestKey(bits)
	if err != nil {
		return err
	}

	rsaCertTuple, certBytes, err := generateSelfSignedCert(key, name)
	if err != nil {
		return err
	}
	fmt.Println("generated certificate expiring on", rsaCertTuple.Cert.NotAfter.Format(time.RFC3339))

	// write private key
	relativeKeyPath, relativeCertPath := dir.LocalKeyPath(name)
	configFS := dir.ConfigFS()
	keyPath, err := configFS.SysPath(relativeKeyPath)
	if err != nil {
		return err
	}
	certPath, err := configFS.SysPath(relativeCertPath)
	if err != nil {
		return err
	}
	if err := osutil.WriteFileWithPermission(keyPath, keyBytes, 0600, false); err != nil {
		return fmt.Errorf("failed to write key file: %v", err)
	}
	fmt.Println("wrote key:", keyPath)

	// write the self-signed certificate
	if err := osutil.WriteFileWithPermission(certPath, certBytes, 0644, false); err != nil {
		return fmt.Errorf("failed to write certificate file: %v", err)
	}
	fmt.Println("wrote certificate:", certPath)

	// update signingkeys.json config
	exec := func(s *config.SigningKeys) error {
		return s.Add(name, keyPath, certPath, opts.isDefault)
	}
	if err := config.LoadExecSaveSigningKeys(exec); err != nil {
		return err
	}

	// Add to the trust store
	if err := truststore.AddCert(certPath, "ca", name, true); err != nil {
		return err
	}

	// write out
	fmt.Printf("%s: added to the key list\n", name)
	if opts.isDefault {
		fmt.Printf("%s: mark as default signing key\n", name)
	}
	return nil
}

func generateTestKey(bits int) (*rsa.PrivateKey, []byte, error) {
	key, err := rsa.GenerateKey(rand.Reader, bits)
	if err != nil {
		return nil, nil, err
	}
	keyBytes, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		return nil, nil, err
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyBytes})
	return key, keyPEM, nil
}

func generateCertPEM(rsaCertTuple *testhelper.RSACertTuple) []byte {
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: rsaCertTuple.Cert.Raw})
}

// generateTestCert generates a self-signed non-CA certificate
func generateSelfSignedCert(privateKey *rsa.PrivateKey, name string) (testhelper.RSACertTuple, []byte, error) {
	rsaCertTuple := testhelper.GetRSASelfSignedCertTupleWithPK(privateKey, name)
	return rsaCertTuple, generateCertPEM(&rsaCertTuple), nil
}

func generateTestCleanUp(keyName string) error {
	var finalError []error
	err := config.LoadExecSaveSigningKeys(func(keys *config.SigningKeys) error {
		keySuite, err := keys.Get(keyName)
		if err != nil {
			return err
		}
		if keySuite.ExternalKey != nil {
			return errors.New("generate-test clean up can only apply to non-external keys")
		}
		if keySuite.X509KeyPair == nil {
			return errors.New("generate-test clean up requires key pair files")
		}
		// delete the certificate from trust store
		certFile := keyName + dir.LocalCertificateExtension
		err = truststore.DeleteCert("ca", keyName, certFile, true)
		if err != nil {
			finalError = append(finalError, fmt.Errorf("cannot delete certificate from truststore/ca/%s/%s during generate-test clean up, %v", keyName, certFile, err))
		}
		// delete the key file from keyPath
		keyPath := keySuite.X509KeyPair.KeyPath
		err = osutil.DeleteFile(keyPath)
		if err != nil {
			finalError = append(finalError, fmt.Errorf("cannot delete the key file from %q during generate-test clean up, %v", keyPath, err))
		} else {
			fmt.Printf("Successfully deleted the key file from %q\n", keyPath)
		}
		// delete the certificate file from certPath
		certPath := keySuite.X509KeyPair.CertificatePath
		err = osutil.DeleteFile(certPath)
		if err != nil {
			finalError = append(finalError, fmt.Errorf("cannot delete the certificate file from %q during generate-test clean up, %v", certPath, err))
		} else {
			fmt.Printf("Successfully deleted the certificate file from %q\n", certPath)
		}
		// remove the key from Notation's signing key list
		_, err = keys.Remove(keyName)
		if err != nil {
			finalError = append(finalError, fmt.Errorf("cannot remove %q from notation signing key list during generate-test clean up, %v", keyName, err))
		} else {
			fmt.Printf("Successfully removed %q from notation signing key list\n", keyName)
		}
		return nil
	})
	if err != nil {
		return err
	}

	// check if there is any error in the process of deletions
	if len(finalError) > 0 {
		for _, err := range finalError {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		}
		return errors.New("failed to complete the generate-test clean up, manual deletion may be needed")
	}
	return nil
}
