on:
  issues:
    types:
      - opened

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@0a99102a6562a4307b8bbc995c279ba01f217d91 # main
        with:
          project-url: https://github.com/orgs/notaryproject/projects/10
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}